### ISSUE TITLE
Cell at certain indexPath for FlowLayoutHorizontalJustificationLeft not set to correct left sectionInset for larger width cells

### ISSUE THREAD

**Issue by eroth** [eroth/ERJustifiedFlowLayout#4]
In the example project (ERViewController) under the following conditions:

```
self.customJustifiedFlowLayout.horizontalJustification = FlowLayoutHorizontalJustificationLeft;
self.customJustifiedFlowLayout.horizontalCellPadding = 5;
self.customJustifiedFlowLayout.sectionInset = UIEdgeInsetsMake(10, 20, 0, 20);
```

with xib cell width set to `200`, one `UICollectionViewCell` in the array of `UICollectionViewLayoutAttributes` returned in `[super layoutAttributesForElementsInRect:rect]` is not being laid out properly.  As can be seen in the screenshot, it should be laid out at the `sectionInset.left`-specified value of `20` but is instead much further out than that.

Note: Issue #2 being fixed or unfixed did not appear to influence this issue.

![ios simulator screen shot aug 12 2015 11 32 14 pm](https://cloud.githubusercontent.com/assets/1851313/9242093/67a605ca-414a-11e5-8a79-bc76d6ca90d4.png)

**Comment by Sega-Zero** [comment]
pretty weird, i see this with this configuration:
![ios simulator screen shot 13 2015 15 48 23](https://cloud.githubusercontent.com/assets/2203199/9250050/ce6d5ba4-41d2-11e5-828c-43f6d54113cb.png)
in iphone6 8.4 simulator
and this:
![ios simulator screen shot 13 2015 15 50 38](https://cloud.githubusercontent.com/assets/2203199/9250099/17af42c8-41d3-11e5-8b5c-964f78a14f8b.png)
in iphone5s 7.1 simulator

Maybe this is some kind of misconfig in xib?

**Comment by eroth** [comment]
I don't believe you have the width of the cell set to `200` in the xib—see screenshot.

<img width="1168" alt="screen shot 2015-08-13 at 8 59 08 am" src="https://cloud.githubusercontent.com/assets/1851313/9250263/a2f5230a-4199-11e5-9e5a-33245769d8b4.png">

**Comment by Sega-Zero** [comment]
![ercollectionviewcell xib 2015-08-13 16-03-09](https://cloud.githubusercontent.com/assets/2203199/9250343/d1bbff2a-41d4-11e5-8ed3-11220a389a22.jpg)
that's what I have =) The only thing i've changed more is setting a label's `<=` constraint value to 200 instead of 150 because of layout ambiguity.

**Comment by eroth** [comment]
Hmm, I'm not getting any ambiguity warnings on mine—I checked in my changes on my `develop` branch; are you able to pull it in to see my version?

**Comment by Sega-Zero** [comment]
sure. but a little bit later, ok? I'm on my work)

**Comment by eroth** [comment]
No worries! I'm just headed off to work, myself :)

**Comment by Sega-Zero** [comment]
This is indeed related to autolayout config. Your develop branch certainly have the bug, but if you change leading/trailing to this (this is why I had layout ambiguity btw) - everything is working as expected:
![ercollectionviewcell xib 2015-08-13 23-11-03](https://cloud.githubusercontent.com/assets/2203199/9260519/c90344ce-4210-11e5-8ae8-f65020c959ee.jpg)
I'll try to figure out what may cause this problem

**Comment by Sega-Zero** [comment]
I finally figured out why this happens =) This case occurs when the item may be fit in rect width completely with the previous one, but super's method implementation puts the item on the next line, because of flowlayout wrap rules. The solution to this is to patch not only the left coordinate, but also a top coordinate of the item (so as decrement origin.y  of all the next items).

You may easily reproduce the problem with this autolayout config:
![ercollectionviewcell xib edited 2015-08-14 00-23-26](https://cloud.githubusercontent.com/assets/2203199/9262042/bdd73c5e-421a-11e5-80b6-11b6c7108e56.jpg)
which results in this misalignment:
![ios 8 4 12h141 2015-08-14 00-24-24](https://cloud.githubusercontent.com/assets/2203199/9262070/dcd5b3d8-421a-11e5-897f-07af050712c2.jpg)

**Comment by eroth** [comment]
Nice! Yeah, I didn't think it had to do with Auto Layout, since we still had a cell of a certain fixed width.  I'll check this out when I get a chance--appreciate all the help!

**Comment by Sega-Zero** [comment]
I fixed misalignment for left justification, but couldn't do it for right yet =) 0c73c54 and 22093ec commits in #5 fixes the picture above

**Comment by eroth** [comment]
Hmm, I'm seeing this on your branch with xib cell size set to 200 and `FlowLayoutHorizontalJustificationLeft`:

![ios simulator screen shot aug 17 2015 9 03 33 pm](https://cloud.githubusercontent.com/assets/1851313/9320062/bb5dfd76-4523-11e5-965c-b7db15eb2808.png)

And this at 108 with `FlowLayoutHorizontalJustificationLeft`:

![ios simulator screen shot aug 17 2015 9 11 08 pm](https://cloud.githubusercontent.com/assets/1851313/9320166/c34e021e-4524-11e5-8a82-3aca569896a5.png)

**Comment by Sega-Zero** [comment]
Fixed that one more time%) Overcomplicated the code last night, now it's more simple and working

**Comment by eroth** [comment]
Did you push it to the right branch? I don't see it. Thanks!

**Comment by Sega-Zero** [comment]
it's appended to #5. I can remove some commits or make a new pull request from another branch, if you want to

**Comment by eroth** [comment]
Hmm, I did a fetch yesterday when I saw your note about this and didn't see anything.  I can try one when I get home and see if it shows up.

Thanks,
Evan

**Comment by eroth** [comment]
Nice! Good work :+1:
